CREATE SCHEMA IF NOT EXISTS cricinfo;
SET SCHEMA cricinfo;
CREATE TABLE roles (id int NOT NULL, name VARCHAR(100) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE players (id int NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, nationality VARCHAR(100) NOT NULL, dob DATE NOT NULL, PRIMARY KEY (id));